---
title: "script to make multipanel figure 2"
output: html_notebook
---

```{r}
library(ggplot2)
library(here)
library(cowplot)
library(gridExtra)
```
#Figure 2

load figures
```{r}

load(here("figures", "Fig_2_a.RData"))
load(here("figures", "Fig_2_b.RData"))
load(here("figures", "Fig_2_c.RData"))
load(here("figures", "Fig_2_d.RData"))
load(here("figures", "Fig_2_e.RData"))
load(here("figures", "Fig_2_f.RData"))
```


arrange figures
```{r}
Fig_2_a <- 
Fig_2_a +
  theme(legend.position = "none")+
  labs(x = "")+
  theme(axis.title.y = element_text(vjust = -4) )


Fig_2_b <- Fig_2_b+
  labs(x = "")+
  theme(axis.title.y = element_text(vjust = -4) )
  
Fig_2_c <- Fig_2_c +
  theme(legend.position ="none")+
  labs(x = "", y = "transgressive\noveryielding")+
  theme(axis.title.y = element_text(vjust = -4) )

Fig_2_d <- Fig_2_d+
  theme(axis.title.y = element_text(vjust = -4),
        legend.position = "none")+
  labs(y = paste("production\n(x", expression(1e8), ")", sep = ""))

Fig_2_e <- Fig_2_e +
  theme(legend.position ="none")+
  theme(axis.title.y = element_text(vjust = -4) )

Fig_2_f <- Fig_2_f+
  labs(y = "transgressive\noveryielding")+
  theme(axis.title.y = element_text(vjust = -4) )


legend <- get_legend(
  # create some space to the left of the legend
  Fig_2_a + 
    guides(color = guide_legend(nrow = 1))+
    theme(legend.position = "bottom")+
    theme(legend.box.margin = margin(0, 0, 0, 0))
)

p1 <- plot_grid(Fig_2_a, Fig_2_b, Fig_2_c, 
                Fig_2_d, Fig_2_e, Fig_2_f, 
                align = "v", labels="AUTO",
                label_x = 0.1)

p1 <- plot_grid(p1, legend, ncol = 1,  rel_heights = c(1, .1))
         
p1

ggsave(plot = p1, filename = here("figures", "Fig_2.pdf"), width = 9, height = 6)


```

#Figure S1
load figures
```{r}
load(here("figures", "Fig_S2_a.RData"))
load(here("figures", "Fig_S2_b.RData"))
load(here("figures", "Fig_S2_c.RData"))
load(here("figures", "Fig_S2_d.RData"))
load(here("figures", "Fig_S2_e.RData"))
load(here("figures", "Fig_S2_f.RData"))
```


arrange figures
```{r}
Fig_S2_a <- 
Fig_S2_a +
  theme(legend.position = "none")+
  labs(x = "")+
  theme(axis.title.y = element_text(vjust = -4) )


Fig_S2_b <- Fig_S2_b+
  labs(x = "")+
  theme(axis.title.y = element_text(vjust = -4) )
  
Fig_S2_c <- Fig_S2_c +
  theme(legend.position ="none")+
  labs(x = "", y = "transgressive\noveryielding")+
  theme(axis.title.y = element_text(vjust = -4) )

Fig_S2_d <- Fig_S2_d+
  theme(axis.title.y = element_text(vjust = -4),
        legend.position = "none")+
  labs(y = paste("production\n(x", expression(1e8), ")", sep = ""))

Fig_S2_e <- Fig_S2_e +
  theme(legend.position ="none")+
  theme(axis.title.y = element_text(vjust = -4) )

Fig_S2_f <- Fig_S2_f+
  labs(y = "transgressive\noveryielding")+
  theme(axis.title.y = element_text(vjust = -4) )


legend <- get_legend(
  # create some space to the left of the legend
  Fig_S2_a + 
    guides(color = guide_legend(nrow = 1))+
    theme(legend.position = "bottom")+
    theme(legend.box.margin = margin(0, 0, 0, 0))
)

p1 <- plot_grid(Fig_S2_a, Fig_S2_b, Fig_S2_c, 
                Fig_S2_d, Fig_S2_e, Fig_S2_f, 
                align = "v", labels="AUTO",
                label_x = 0.1)

p1 <- plot_grid(p1, legend, ncol = 1,  rel_heights = c(1, .1))
         
p1

ggsave(plot = p1, filename = here("figures", "Fig_S2.pdf"), width = 9, height = 6)


```
